// Copyright (c) 2025 IBM Corp.
// All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package attestation

import (
	"fmt"

	decrypt "github.com/ibm-hyper-protect/contract-go/v2/common/decrypt"
	enc "github.com/ibm-hyper-protect/contract-go/v2/common/encrypt"
	gen "github.com/ibm-hyper-protect/contract-go/v2/common/general"
)

const (
	missingParameterErrStatement = "required parameter is missing"
)

// HpcrGetAttestationRecords decrypts encrypted attestation records generated by IBM
// Confidential Computing services.
//
// Use this function to decrypt the attestation records received from a deployed IBM Confidential
// Computing instance. Attestation records provide a cryptographic proof that the workload is
// running in a genuine IBM Secure Execution environment. The encrypted attestation data is
// decrypted using the RSA private key corresponding to the attestationPublicKey provided in
// the original contract.
//
// Parameters:
//   - data: Encrypted attestation data in the format "contract-basic.<encrypted-password>.<encrypted-data>"
//   - privateKey: RSA private key (PEM format) corresponding to the attestationPublicKey used in the contract
//   - password: Optional password to unlock the private key if it's encrypted (empty string "" for unencrypted keys)
//
// Returns:
//   - Decrypted attestation records string (typically se-checksums.txt content)
//   - Error if decryption fails or parameters are missing
func HpcrGetAttestationRecords(data, privateKey, password string) (string, error) {
	if gen.CheckIfEmpty(data, privateKey) {
		return "", fmt.Errorf(missingParameterErrStatement)
	}

	attestationRecords, err := decrypt.DecryptText(data, privateKey, password)
	if err != nil {
		return "", fmt.Errorf("failed to decrypt attestation records - %v", err)
	}

	return attestationRecords, nil
}

// HpcrVerifySignatureAttestationRecords verifies the signature of decrypted attestation records
// against an IBM attestation certificate.
//
// Use this function after decrypting attestation records with [HpcrGetAttestationRecords] to verify
// that the records were genuinely signed by IBM and have not been tampered with. This is important
// for audit and compliance workflows where you need cryptographic proof that the workload ran in
// an authentic IBM Secure Execution environment.
//
// The function extracts the public key from the IBM attestation certificate and uses it to
// verify the signature against the decrypted attestation records.
//
// Parameters:
//   - attestationRecords: Decrypted attestation records (output from [HpcrGetAttestationRecords],
//     typically the content of se-checksums.txt)
//   - signature: Binary signature data (typically the content of se-signature.bin as string)
//   - attestationCert: IBM attestation certificate in PEM format (obtained from the runtime image)
//
// Returns:
//   - nil if the signature verification succeeds (records are authentic)
//   - Error if verification fails, indicating the records may have been tampered with
func HpcrVerifySignatureAttestationRecords(attestationRecords, signature, attestationCert string) error {
	if gen.CheckIfEmpty(attestationRecords, attestationCert, signature) {
		return fmt.Errorf(missingParameterErrStatement)
	}

	// Extract public key from certificate using OpenSSL
	publicKey, err := enc.ExtractPublicKeyFromCert(attestationCert)
	if err != nil {
		return fmt.Errorf("failed to extract public key from certificate - %v", err)
	}

	// Verify signature using OpenSSL
	err = enc.VerifySignature(attestationRecords, signature, publicKey)
	if err != nil {
		return fmt.Errorf("signature verification failed - %v", err)
	}

	return nil
}
